### ISSUE TITLE
Weeky Ruby Script Runner bug

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2807]
https://github.com/slurpcode/slurp/actions/runs/11282521023/job/31380130394

Failed with red

**Comment by jbampton** [comment]
@Dxuian

**Comment by BaseMax** [comment]
> https://github.com/slurpcode/slurp/actions/runs/11282521023/job/31380130394


The logs for this run have expired and are no longer available.


Can you please share new logs or link of logs? so i can check.

**Comment by BaseMax** [comment]
I would like to work on it. not sure if @Dxuian is available to do it.

**Comment by jbampton** [comment]
Thanks @BaseMax you are now assigned

**Comment by BaseMax** [comment]
https://github.com/slurpcode/slurp/actions/runs/15099518805/job/42438629238

```
/opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/mechanize-2.14.0/lib/mechanize/http/agent.rb:340:in `fetch': 403 => Net::HTTPForbidden for https://www.seek.com.au/ -- unhandled response (Mechanize::ResponseCodeError)
	from /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/mechanize-2.[14](https://github.com/slurpcode/slurp/actions/runs/15099518805/job/42438629238#step:5:15).0/lib/mechanize.rb:483:in `get'
	from seek/new.rb:12:in `fetch_main_page'
	from seek/new.rb:102:in `scrape_and_process'
	from seek/new.rb:127:in `<main>'
Attempt 1 of 3
Error: Process completed with exit code 1.
```

Is this same issue?

**Comment by Dxuian** [comment]
ill try to look at it
